import { Project, Category, User } from '@/types';

export const mockUser: User = {
  id: '1',
  name: 'Ana García',
  email: 'ana@example.com',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ana',
  bio: 'Emprendedora social apasionada por el cambio',
  location: 'Madrid, España',
  role: 'both',
  createdAt: '2024-01-15',
};

export const categories: Category[] = [
  { id: '1', name: 'Tecnología', slug: 'tecnologia', icon: 'Laptop' },
  { id: '2', name: 'Sostenibilidad', slug: 'sostenibilidad', icon: 'Leaf' },
  { id: '3', name: 'Arte y Diseño', slug: 'arte-diseno', icon: 'Palette' },
  { id: '4', name: 'Educación', slug: 'educacion', icon: 'GraduationCap' },
  { id: '5', name: 'Impacto Social', slug: 'impacto-social', icon: 'Heart' },
  { id: '6', name: 'Música', slug: 'musica', icon: 'Music' },
];

export const mockProjects: Project[] = [
  {
    id: '1',
    title: 'Moda Sostenible: Ropa del Futuro',
    description: 'Creamos ropa 100% sostenible usando materiales reciclados y técnicas artesanales. Nuestro objetivo es demostrar que la moda puede ser hermosa, ética y respetuosa con el planeta.',
    shortDescription: 'Ropa 100% sostenible con materiales reciclados',
    category: 'Sostenibilidad',
    creatorId: '1',
    creator: mockUser,
    goalAmount: 5000,
    currentAmount: 3200,
    currency: 'EUR',
    image: '/src/assets/project-1.jpg',
    status: 'active',
    daysLeft: 15,
    supportersCount: 42,
    createdAt: '2024-10-01',
    featured: true,
  },
  {
    id: '2',
    title: 'App para Conectar Emprendedores',
    description: 'Una plataforma móvil que conecta jóvenes emprendedores con mentores, recursos y oportunidades de financiación. Facilitamos el networking y el aprendizaje colaborativo.',
    shortDescription: 'Conecta emprendedores con mentores y recursos',
    category: 'Tecnología',
    creatorId: '2',
    creator: {
      id: '2',
      name: 'Carlos Ruiz',
      email: 'carlos@example.com',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos',
      role: 'creator',
      createdAt: '2024-02-20',
    },
    goalAmount: 8000,
    currentAmount: 5600,
    currency: 'EUR',
    image: '/src/assets/project-2.jpg',
    status: 'active',
    daysLeft: 22,
    supportersCount: 67,
    createdAt: '2024-09-15',
    featured: true,
  },
  {
    id: '3',
    title: 'Huertos Urbanos Comunitarios',
    description: 'Transformamos espacios abandonados en huertos comunitarios donde los vecinos pueden cultivar sus propios alimentos, aprender sobre agricultura urbana y construir comunidad.',
    shortDescription: 'Espacios verdes compartidos en la ciudad',
    category: 'Impacto Social',
    creatorId: '3',
    creator: {
      id: '3',
      name: 'María López',
      email: 'maria@example.com',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
      role: 'creator',
      createdAt: '2024-03-10',
    },
    goalAmount: 3000,
    currentAmount: 2100,
    currency: 'EUR',
    image: '/src/assets/project-3.jpg',
    status: 'active',
    daysLeft: 30,
    supportersCount: 38,
    createdAt: '2024-09-20',
    featured: true,
  },
];
